dist: xenial
language: haskell
ghc:
  - 8.6.4
addons:
  apt:
    packages:
      - xz-utils
env: TARGET=x86_64-unknown-linux-gnu

install:
  - cabal install --dependencies-only --ghc-options="-optlo-O3 -split-sections"

script:
  # Remove all tests to reduce binary size
  - ./striptests
  - cabal build Paths_ShellCheck
  - ghc -optl-static -optl-pthread -isrc -idist/build/autogen --make shellcheck -split-sections -optc-Wl,--gc-sections -optlo-O3
  - strip --strip-all shellcheck
  - ls -l shellcheck
  - printf '%s\n' "#!/bin/sh" "echo 'hello world'" > myscript
  - ./shellcheck myscript

before_deploy:
  - cp ./shellcheck ./shellcheck-${TARGET}

deploy:
  - provider: releases
    file_glob: true
    file: shellcheck-${TARGET}
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: "$GH_TOKEN"
